development:
  server: "http://localhost:9292/faye"
  secret_token: "secret"
test:
  server: "http://localhost:9292/faye"
  secret_token: "secret"
production:
production:
  server: "https://fayeserver-demo.herokuapp.com/faye"
  secret_token: 'batkaro'
  signature_expiration: 86400 # one day
